{
	"version": 1488776503,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/menutop-sheet0.png",
		"images/credits-sheet0.png",
		"images/down-sheet0.png",
		"images/help-sheet0.png",
		"images/leftbutton-sheet0.png",
		"images/playgame-sheet0.png",
		"images/menubutton-sheet0.png",
		"images/menubutton-sheet1.png",
		"images/soundon-sheet0.png",
		"images/soundon-sheet1.png",
		"images/fundo-sheet0.png",
		"images/top-sheet0.png",
		"images/bottom-sheet0.png",
		"images/block-sheet0.png",
		"images/blockimage-sheet0.png",
		"images/blockimage-sheet1.png",
		"images/box-sheet0.png",
		"images/boxfront-sheet0.png",
		"images/segurator-sheet0.png",
		"images/keepposition-sheet0.png",
		"images/endcall-sheet0.png",
		"images/extrapoints-sheet0.png",
		"images/movimentcontrol-sheet0.png",
		"images/menubottom-sheet0.png",
		"images/menufloating.png",
		"images/backgroungrey.png",
		"images/backgroundwhite.png",
		"images/background-sheet0.png",
		"images/herbivore-sheet0.png",
		"images/carnivore-sheet0.png",
		"images/autotroph-sheet0.png",
		"images/decomposer-sheet0.png",
		"images/primary-sheet0.png",
		"images/secondary-sheet0.png",
		"images/tertiary-sheet0.png",
		"images/questiona-sheet0.png",
		"images/pyramid-sheet0.png",
		"images/foodweblines-sheet0.png",
		"media/319419__johnthewizar__selection-sounds.m4a",
		"media/319419__johnthewizar__selection-sounds.ogg",
		"media/bloco caindo__lollosound__25-fiaccola-pass.m4a",
		"media/bloco caindo__lollosound__25-fiaccola-pass.ogg",
		"media/blocobom__josepharaoh99__comical-sprout.m4a",
		"media/blocobom__josepharaoh99__comical-sprout.ogg",
		"media/caixa engolindo__callum-sharp279__modificado.m4a",
		"media/caixa engolindo__callum-sharp279__modificado.ogg",
		"media/errado__kevinvg207__wrong-buzzer.m4a",
		"media/errado__kevinvg207__wrong-buzzer.ogg",
		"media/hittingbutton__nenadsimic__button-tick.ogg",
		"media/passagem de fase - spring time - chipola.m4a",
		"media/passagem de fase - spring time - chipola.ogg",
		"media/switch__rutgermuller__light-switch.ogg",
		"media/fm_long positive stinger 1.ogg",
		"media/farmfulllopeditado.m4a",
		"media/farmfulllopeditado.ogg",
		"media/passaros__y-t__various-birds-europe-germany-singing-in-the-morning-filtered.m4a",
		"media/passaros__y-t__various-birds-europe-germany-singing-in-the-morning-filtered.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}